# Generated by Django 4.1.3 on 2023-07-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_transform',
            name='source_table',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
