# Generated by Django 4.1.3 on 2023-07-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0002_d_transform_source_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema_migration',
            old_name='mail',
            new_name='email',
        ),
    ]
