# Generated by Django 4.1.3 on 2023-07-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0003_rename_mail_schema_migration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_transform',
            name='source_table',
        ),
    ]
