# Generated by Django 4.1.3 on 2023-07-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0004_remove_d_transform_source_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_transform',
            name='schema_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
